name: Greg Zynda
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
#destination: /u/gjzynda/html-pub/served
#baseurl: /gjzynda/served
paginate: 5
navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
exclude: [oldsite]
future: true
