name: Greg Zynda
markdown: redcarpet2
redcarpet:
  extensions: ["tables"]
pygments: true
#destination: /u/gjzynda/html-pub/served
#baseurl: /gjzynda/served
paginate: 5
navigation:
  title: Home
  url: /index.html
  title: About
  url: /about.html
exclude: [oldsite]
